export const personalInfo = {
  name: "Lucas UZAN",
  location: "Toulouse, France",
  email: "uzanlah@gmail.com",
  github: "https://github.com/wiiz83",
  linkedin: "https://www.linkedin.com/in/lucasuzan/",
};

export const workExperience = [
  {
    company: "Sopra Steria",
    location: "Toulouse, France",
    position: "Product Owner / Business Analyst",
    period: "Oct 2022 – Present",
    achievements: [
      "Collecting business requirements, writing user stories, creating wireframes, testing features.",
      "Leading workshops and estimation sessions with cross-functional teams.",
      "Writing and executing test strategies (Cypress, Xray) to ensure 100% code coverage.",
      "Owning the functional scope and rationalising documentation across teams.",
      "Supporting adoption of prototyping tools (Balsamiq) and agile process improvements.",
      "Assisting the Scrum Master in enhancing team rituals and internal wiki content.",
    ],
  },
  {
    company: "DataMedCare",
    location: "Bordeaux, France",
    position: "Full-stack Developer / Scrum Master",
    period: "2020 – 2022",
    achievements: [
      "Developed frontend interfaces and backend logic (APIs, database integration).",
      "Modelled, queried, and optimised database structures.",
      "Deployed solutions to production and ensured bug resolution.",
      "Introduced Agile practices (Scrumban), led Scrum ceremonies.",
      "Collaborated on UI/UX design using Figma with business teams.",
      "Migrated to Atlassian (Confluence, Jira) suite with structured backlog.",
    ],
  },
  {
    company: "Air France",
    location: "Toulouse, France",
    position: "Full-stack Developer (apprenticeship)",
    period: "2017 – 2019",
    achievements: [
      "Developed a multilingual VoiceBot (IBM/Google stack) and tracking dashboards.",
      "Worked directly with business stakeholders in an international SAFe context.",
    ],
  },
  {
    company: "Océalia Informatique",
    location: "Toulouse, France",
    position: "Software Developer (apprenticeship)",
    period: "2016 – 2017",
    achievements: [
      "Designed and rebuilt a staff scheduling solution for the social/healthcare sector.",
    ],
  },
  {
    company: "L'écofabrique",
    location: "Toulouse, France",
    position: "Freelance Web Developer",
    period: "2017 – 2019",
    achievements: [
      "Développement d’un site e-commerce de consommation responsable.",
      "Conducted UX audits, created e-commerce and institutional websites.",
    ],
  },
  {
    company: "Alpamayo",
    location: "Grenoble, France",
    position: "Freelance Web Developer",
    period: "2017 – 2019",
    achievements: [
      "Développement d’un site web de sectorisation scolaire.",
      "Conducted UX audits, created e-commerce and institutional websites.",
    ],
  },
  {
    company: "DJ Gwada + DJ Rory",
    location: "Cork, Ireland",
    position: "Freelance Graphic Designer",
    period: "2017 – 2019",
    achievements: [
      "Création d’affiches d’événements pour musiciens en Irlande.",
    ],
  },
];

export const education = [
  {
    institution: "Université Toulouse Capitole",
    location: "Toulouse, France",
    degree: "Master in Computer Science & Business (MIAGE)",
    period: "2017 - 2019",
    achievements: [
      "Project Management Methodology",
      "Information Systems Quality",
      "Software Engineering",
      "Data Decentralization",
      "Networks",
      "Financial Analysis of Projects",
      "Resource Processes",
      "Artificial Intelligence: Problem Representation and Solving",
      "Linear Optimization of Complex Problems",
      "Object-Oriented Analysis Methodology",
      "Process Management",
      "Enterprise Applications",
      "Data and Risk Management",
      "User-Centered Applications",
      "Integrated Software Packages (ERP)",
      "Law and Auditing",
      "Communication and Languages",
      "AL3C Innovation Project",
    ],
  },
  {
    institution: "Université Toulouse Capitole",
    location: "Toulouse, France",
    degree: "Bachelor in Computer Science & Business (MIAGE)",
    period: "2016 - 2017",
    achievements: [
      "Harmonization: Mathematics, Computer Science, Management, Information Systems",
      "Networks and Services",
      "Data Representation, Storage, and Querying",
      "Object-Oriented Design and Tooling",
      "Mathematics for Computer Science and Organization",
      "Labor Economics and Law",
      "Project Management",
      "Information and Decision-Making",
      "Communication and Languages: Writing, Sociology, English",
      "Web 2.0 Applications",
      "Database Standardization and Implementation",
      "Concurrent Object-Oriented Applications and Project",
      "Statistical Tools",
      "Systemic Methods and Development",
      "Financial Management",
      "IT Project Management",
    ],
  },
  {
    institution: "Université Grenoble Alpes",
    location: "Grenoble, France",
    degree: "Bachelor in Computer Science ",
    period: "2015 - 2016",
    achievements: [
      "Software and Hardware Architectures",
      "Algorithmics",
      "Databases (Relational Algebra, SQL, Datalog)",
      "Syntax Analysis",
      "Systems and Networks",
      "Models of Computation (Turing Machine, Lambda Calculus)",
      "C and Java Programming Languages",
      "Graphics Programming",
    ],
  },
  {
    institution: "Munster Technological University",
    location: "Cork, Ireland",
    degree: "Bachelor in Computer Science",
    period: "2014 - 2015",
    achievements: [
      "Android Application Development (Java / XML)",
      "User Interface Development (Java)",
      "Dynamic Web Development (PHP / SQL)",
      "Ubuntu Linux Administrator (Server & Desktop)",
      "IT-Oriented Management (Information Systems…)",
      "Requirements Engineering (Use Cases, UML…)",
      "Human-Computer Interaction (HCI)",
    ],
  },
  {
    institution: "Université Grenoble Alpes",
    location: "Grenoble, France",
    degree: "DUT Services et réseaux de communication",
    period: "2012 - 2014",
    achievements: [
      "Web development (HTML, CSS, PHP, SQL, JS)",
      "Graphic design — flyers, logos, web design, etc.",
      "Audiovisual production — filming, editing, post-production, etc.",
      "Law, economics, project management, marketing",
      "Information and Communication Technologies (ICT)",
      "Written and oral communication",
    ],
  },
];
export const skills = {
  programmingLanguages: [
    "C#",
    "Python",
    "TypeScript",
    "SQL",
    "NoSQL",
    "JavaScript",
    "Java",
  ],
  aiDevelopment: [
    "NumPy",
    "PyTorch",
    "Machine Learning (Regression)",
    "Deep Learning (CNN)",
    "RAG (Weaviate)",
    "Pipeline (Airflow, Astronomer)",
    "AI-assisted coding (Cursor AI)",
  ],
  frontendDevelopment: [
    "Angular",
    "Angular Material",
    "HTML",
    "CSS",
    "Bootstrap",
  ],
  backendDevelopment: [
    ".NET Core",
    "FastAPI",
    "NestJS",
    "Node.js", 
    "FastAPI",
    "Spring Boot",
  ],
  testingDevelopment: [
    "Cypress",
    "Xray Test Management",
    "Postman",
    "Insomnia",
    "SoapUI"
  ],
  databaseAndStorage: [
    "SQL Server",
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "SQLite",
  ],
  cloudAndDevOps: [
    "Firebase",
    "GCP",
    "Docker",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
  ],
  toolsAndServices: [
    "REST",
    "SOAP",
    "WebSockets",
  ],
  designTools: [
    "Balsamiq",
    "Figma",
    "Adobe XD",
    "Adobe Photoshop",
    "Adobe Illustrator",
  ],
  productAndAgile: [
    "Scrum",
    "SAFe 6",
    "Kanban ",
    "Product backlog management",
    "Prioritisation",
    "Roadmap",
  ],
  modellingAndDocumentation: [
    "UML & Merise modelling",
    "Functional Specifications",
    "User Research",
  ],
};

export const projects = [
  {
    title: "Net Zero Carbon Emissions",
    github: "https://github.com/rishikesh2003/Prodigi",
    description: [
      "WiFi-RTT: Developed indoor occupancy tracking for energy optimization.",
      "IoT Solutions: Implemented smart monitoring for energy efficiency and food waste reduction.",
      "Real-Time Tracking: Designed systems to monitor carbon emissions and optimize resources.",
      "Data-Driven Insights: Analyzed user patterns for adaptive energy and food management.",
      "Reward Integration: Built QR-based green points system to incentivize eco-friendly actions.",
    ],
  },
  {
    title: "Mental Aarog",
    github: "https://github.com/rishikesh2003/mental-aarog",
    description: [
      "A holistic mental health app leveraging AI and blockchain for early detection and personalized solutions for depression.",
      "Features include social media analysis (ML-based sentiment tracking), PHQ-9 assessments, smartwatch integration for sleep and activity data, guided meditation, and smart suggestions for food, travel, music, and movies.",
      "Developed a rewards system using MAG crypto token on Ethereum, enabling user engagement through in-app incentives.",
      "Secure storage implemented via web3.storage, IPFS, and FileCoin.",
      "Built with React, Supabase, Node.js, Flask, and Solidity, showcasing seamless integration of health tech and blockchain.",
    ],
  },
];

export const awards = [
  {
    name: "IEEE YESIST12 Hackathon",
    issuer: "IEEE",
    date: "Sep 2022",
    type: "International",
    position: "Second Place",
  },
  {
    name: "Prodigi Cognizant Hackathon",
    issuer: "Cognizant",
    date: "Feb 2023",
    type: "National",
    position: "Second Runner-up",
  },
  {
    name: "Cisco Thingqbator Hackathon",
    issuer: "Cisco",
    date: "Jan 2023",
    type: "National",
    position: "First Runner-up",
  },
  {
    name: "Innovators Day",
    issuer: "Sri Manakula Vinayagar Engineering College, Pondicherry",
    date: "Sep 2022",
    type: "National",
    position: "First Prize",
  },
  {
    name: "KG Hackfest'22",
    issuer: "KGiSL Institute of Technology, Coimbatore",
    date: "Sep 2022",
    type: "National",
    position: "Second Prize",
  },
  {
    name: "Innohacks'22",
    issuer: "Innogeeks, KIET Group of Institutions, New Delhi",
    date: "May 2022",
    type: "National",
    position: "Second Runner-up",
  },
  {
    name: "Hack @ SKCET",
    issuer: "Hackclub SKCET, SKCET, Coimbatore",
    date: "Feb 2022",
    type: "National",
    position: "Most Impactful Hack",
  },
];
