export const personalInfo = {
  name: "Lucas UZAN",
  location: "Toulouse, France",
  position: "Full-stack Developer | Product-Driven Mindset | AI & UX Enthusiast",
  email: "uzanlah@gmail.com",
  github: "https://github.com/wiiz83",
  linkedin: "https://www.linkedin.com/in/lucasuzan/",
};

export const workExperience = [
  {
    company: "Pyto",
    location: "Remote",
    website: "https://pyto.eu/",
    position: "Co-founder",
    period: "2024 – Present",
    context: "Create a mobile application helping plant lovers care for their plants",
    responsibilities: [
      "Market research, business planning, partner scouting.",
      "Project management: scheduling, meeting coordination, strategic decisions.",
      "Wireframing and collaboration with professional designers.",
      "Product management in close collaboration with users and business partners.",
      "Technical architecture design (FastAPI, React Native, PostgreSQL).",
      "MVP development leveraging AI tools (Cursor AI, ChatGPT).",
      "Image recognition AI development (EfficientNet B0).",
      "CI/CD deployment with Docker and GitHub Actions.",
      "Integration with external services (Mistral AI, OpenWeatherMap, Firebase).",
      "Market analysis, business plan development and partner research",
      "Leading product development, MVP design and technical architecture",
      "Working closely with graphic designers, plant lovers and plant businesses",
    ],
    achievements: [
    ],
  },
  {
    company: "Sopra Steria",
    location: "Toulouse, France",
    website: "https://www.soprasteria.com/",
    position: "Business Analyst / Product Owner",
    period: "Oct 2022 – Present",
    context: "Sectors: Defence (DGATA), Telecommunications (Orange)",
    responsibilities: [
      "Collecting business requirements, writing user stories, creating wireframes, testing features.",
      "Leading workshops and estimation sessions with cross-functional teams.",
      "Writing and executing test strategies (Cypress, Xray) to ensure 100% code coverage.",
      "Owning the functional scope and rationalising documentation across teams.",
      "Supporting adoption of prototyping tools (Balsamiq) and agile process improvements.",
      "Assisting the Scrum Master in enhancing team rituals and internal wiki content.",
      "Functional requirements analysis and mockup design",
      "Estimation of functional solutions and dev tickets with the team",
      "Frequent and close collaboration with the client via workshops",
      "Writing functional requirements, test scenarios, and development tickets",
      "Supporting the dev team in understanding business needs, often in English",
      "Testing developments using UI, Excel, SQL, and Python",
      "Implementing functional tests with Cypress (Angular context)",
      "Suggesting improvements to the client",
    ],
    achievements: [
    ],
  },
  {
    company: "DataMedCare",
    location: "Bordeaux, France",
    website: "https://www.datamedcare.com/",
    position: "Full-stack Developer / Scrum Master",
    period: "2020 – 2022",
    context: "Enhance web applications to monitor patients with sleep apnea",
    responsibilities: [
      "Developed frontend interfaces and backend logic (APIs, database integration).",
      "Modelled, queried, and optimised database structures.",
      "Deployed solutions to production and ensured bug resolution.",
      "Introduced Agile practices (Scrumban), led Scrum ceremonies.",
      "Collaborated on UI/UX design using Figma with business teams.",
      "Migrated to Atlassian (Confluence, Jira) suite with structured backlog.",
      "Development of new features and maintenance of existing projects.",
      "Close collaboration with developers, PO, and business stakeholders.",
      "Implemented agile workflow (Scrumban) tailored to the company.",
      "Facilitated Scrum ceremonies and continuous improvement.",
      "Wireframing and mockup updates with Figma.",
    ],
    achievements: [
    ],
  },
  {
    company: "Air France",
    location: "Toulouse, France",
    website: "https://wwws.airfrance.fr/",
    position: "Full-stack Developer (apprenticeship)",
    period: "2017 – 2019",
    context: "Create a multilingual customer VoiceBot and tracking dashboards",
    responsibilities: [
      "Developed a multilingual VoiceBot (IBM/Google stack) and tracking dashboards.",
      "Worked directly with business stakeholders in an international SAFe context.",
      "Evolutive maintenance of internally developed projects.",
      "Developed a voice assistant (VoiceBot) for customer service:.",
      "PoC, need gathering, UML design, UI mockups.",
      "Front-end in Angular 7 for KPIs and stats.",
      "Back-end with Spring Boot (GDPR-compliant encryption).",
      "MongoDB setup for call log storage.",
      "CI tools: Bamboo, Cloud Foundry, Docker, Sonar, Bitbucket.",
      "IBM and Google technologies (Watson, Voice Gateway, TTS/STT).",
      "Agile (SAFe) environment, direct business interaction, often in English.",
    ],
    achievements: [
    ],
  },
  {
    company: "Océalia Informatique",
    location: "Toulouse, France",
    website: "https://www.ocealia-informatique.com/",
    position: "Software Developer (apprenticeship)",
    period: "2016 – 2017",
    context: "Redesign a staff scheduling solution for the social/healthcare sector",
    responsibilities: [
      "Designed and rebuilt a staff scheduling solution for the social/healthcare sector.",
      "Redesigned a staff scheduling management tool for the healthcare sector :.",
      "UI/UX design using Adobe Photoshop.",
      "Developed the app using WinDev (WLangage, HyperFileSQL).",
      "Supported client meetings and needs gathering.",
    ],
    achievements: [
    ],
  },
  {
    company: "L'écofabrique",
    location: "Toulouse, France",
    website: "",
    position: "Freelance Web Developer",
    period: "2017 – 2019",
    context: "Create a web application for e-commerce",
    responsibilities: [
      "Développement d’un site e-commerce de consommation responsable.",
      "Conducted UX audits, created e-commerce and institutional websites.",
    ],
    achievements: [
    ],
  },
  {
    company: "Alpamayo",
    location: "Grenoble, France",
    website: "https://www.alpamayo.fr/",
    position: "Freelance Web Developer",
    period: "2017 – 2019",
    context: "Redesigned a web application for school zoning data consultation and management",
    responsibilities: [
      "Développement d’un site web de sectorisation scolaire.",
      "Conducted UX audits, created e-commerce and institutional websites.",
      "Performed project analysis and competitive research.",
      "Designed an intuitive user interface.",
      "Developed the front-end using ASP.NET.",
    ],
    achievements: [
    ],
  },
  {
    company: "DJ Gwada Mike",
    location: "Cork, Ireland",
    website: "https://fr.ra.co/dj/djgwadamike",
    position: "Freelance Graphic Designer",
    period: "2017 – 2019",
    context: "",
    responsibilities: [
      "Création d’affiches d’événements pour musiciens en Irlande.",
    ],
    achievements: [
    ],
  },
];

export const education = [
  {
    institution: "Université Toulouse Capitole",
    location: "Toulouse, France",
    degree: "Master in Computer Science & Business (MIAGE)",
    period: "2017 - 2019",
    achievements: [
      "Project Management Methodology",
      "Information Systems Quality",
      "Software Engineering",
      "Data Decentralization",
      "Networks",
      "Financial Analysis of Projects",
      "Resource Processes",
      "Artificial Intelligence: Problem Representation and Solving",
      "Linear Optimization of Complex Problems",
      "Object-Oriented Analysis Methodology",
      "Process Management",
      "Enterprise Applications",
      "Data and Risk Management",
      "User-Centered Applications",
      "Integrated Software Packages (ERP)",
      "Law and Auditing",
      "Communication and Languages",
      "AL3C Innovation Project",
    ],
  },
  {
    institution: "Université Toulouse Capitole",
    location: "Toulouse, France",
    degree: "Bachelor in Computer Science & Business (MIAGE)",
    period: "2016 - 2017",
    achievements: [
      "Harmonization: Mathematics, Computer Science, Management, Information Systems",
      "Networks and Services",
      "Data Representation, Storage, and Querying",
      "Object-Oriented Design and Tooling",
      "Mathematics for Computer Science and Organization",
      "Labor Economics and Law",
      "Project Management",
      "Information and Decision-Making",
      "Communication and Languages: Writing, Sociology, English",
      "Web 2.0 Applications",
      "Database Standardization and Implementation",
      "Concurrent Object-Oriented Applications and Project",
      "Statistical Tools",
      "Systemic Methods and Development",
      "Financial Management",
      "IT Project Management",
    ],
  },
  {
    institution: "Université Grenoble Alpes",
    location: "Grenoble, France",
    degree: "Bachelor in Computer Science ",
    period: "2015 - 2016",
    achievements: [
      "Software and Hardware Architectures",
      "Algorithmics",
      "Databases (Relational Algebra, SQL, Datalog)",
      "Syntax Analysis",
      "Systems and Networks",
      "Models of Computation (Turing Machine, Lambda Calculus)",
      "C and Java Programming Languages",
      "Graphics Programming",
    ],
  },
  {
    institution: "Munster Technological University",
    location: "Cork, Ireland",
    degree: "Bachelor in Computer Science",
    period: "2014 - 2015",
    achievements: [
      "Android Application Development (Java / XML)",
      "User Interface Development (Java)",
      "Dynamic Web Development (PHP / SQL)",
      "Ubuntu Linux Administrator (Server & Desktop)",
      "IT-Oriented Management (Information Systems…)",
      "Requirements Engineering (Use Cases, UML…)",
      "Human-Computer Interaction (HCI)",
    ],
  },
  {
    institution: "Université Grenoble Alpes",
    location: "Grenoble, France",
    degree: "DUT Services et réseaux de communication",
    period: "2012 - 2014",
    achievements: [
      "Web development (HTML, CSS, PHP, SQL, JS)",
      "Graphic design — flyers, logos, web design, etc.",
      "Audiovisual production — filming, editing, post-production, etc.",
      "Law, economics, project management, marketing",
      "Information and Communication Technologies (ICT)",
      "Written and oral communication",
    ],
  },
];
export const skills = {
  programmingLanguages: [
    "C#",
    "Python",
    "TypeScript",
    "SQL",
    "NoSQL",
    "JavaScript",
    "Java",
  ],
  aiDevelopment: [
    "NumPy",
    "PyTorch",
    "Machine Learning (Regression)",
    "Deep Learning (CNN)",
    "RAG (Weaviate)",
    "Pipeline (Airflow, Astronomer)",
    "AI-assisted coding (Cursor AI)",
  ],
  frontendDevelopment: [
    "Angular",
    "Angular Material",
    "HTML",
    "CSS",
    "Bootstrap",
  ],
  backendDevelopment: [
    ".NET Core",
    "FastAPI",
    "NestJS",
    "Node.js", 
    "FastAPI",
    "Spring Boot",
  ],
  testingDevelopment: [
    "Cypress",
    "Xray Test Management",
    "Postman",
    "Insomnia",
    "SoapUI"
  ],
  databaseAndStorage: [
    "SQL Server",
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "SQLite",
  ],
  cloudAndDevOps: [
    "Firebase",
    "GCP",
    "Docker",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
  ],
  toolsAndServices: [
    "REST",
    "SOAP",
    "WebSockets",
  ],
  designTools: [
    "Balsamiq",
    "Figma",
    "Adobe XD",
    "Adobe Photoshop",
    "Adobe Illustrator",
  ],
  productAndAgile: [
    "Scrum",
    "SAFe 6",
    "Kanban ",
    "Product backlog management",
    "Prioritisation",
    "Roadmap",
  ],
  modellingAndDocumentation: [
    "UML & Merise modelling",
    "Functional Specifications",
    "User Research",
  ],
};

export const projects = [
  {
    title: "Net Zero Carbon Emissions",
    github: "https://github.com/rishikesh2003/Prodigi",
    description: [
      "WiFi-RTT: Developed indoor occupancy tracking for energy optimization.",
      "IoT Solutions: Implemented smart monitoring for energy efficiency and food waste reduction.",
      "Real-Time Tracking: Designed systems to monitor carbon emissions and optimize resources.",
      "Data-Driven Insights: Analyzed user patterns for adaptive energy and food management.",
      "Reward Integration: Built QR-based green points system to incentivize eco-friendly actions.",
    ],
  },
  {
    title: "Mental Aarog",
    github: "https://github.com/rishikesh2003/mental-aarog",
    description: [
      "A holistic mental health app leveraging AI and blockchain for early detection and personalized solutions for depression.",
      "Features include social media analysis (ML-based sentiment tracking), PHQ-9 assessments, smartwatch integration for sleep and activity data, guided meditation, and smart suggestions for food, travel, music, and movies.",
      "Developed a rewards system using MAG crypto token on Ethereum, enabling user engagement through in-app incentives.",
      "Secure storage implemented via web3.storage, IPFS, and FileCoin.",
      "Built with React, Supabase, Node.js, Flask, and Solidity, showcasing seamless integration of health tech and blockchain.",
    ],
  },
];

export const awards = [
  {
    name: "IEEE YESIST12 Hackathon",
    issuer: "IEEE",
    date: "Sep 2022",
    type: "International",
    position: "Second Place",
  }
];
